### ISSUE TITLE
Broken UI after register with existing data

### ISSUE THREAD

**Issue by Sh1karno** [AndreySurzhan/ChecklistSLWebUi#37]
**PC**
1. Register page shuld be open
2. User should be registered

**STR**
1. enter existing email in database
2. enter valid password
3. click on register button

**ER**
the error "emeil already exists" should be displayed

**AR**
the error is not displayed, an infinite loading occurs, if the refresh of the UI page is disabled

![screenshot_20190726_203523](https://user-images.githubusercontent.com/51874192/61974647-b6c63b80-afef-11e9-910d-2ea97320c358.jpg)

 **API Log:**
```
2019-08-23T16:41:28.724876+00:00 app[web.1]: 2019-08-23T16:41:28.724Z - [31merror[39m: Failed to create new user test@test.com
2019-08-23T16:41:28.725608+00:00 app[web.1]: 2019-08-23T16:41:28.724Z - [31merror[39m:  message=E11000 duplicate key error index: heroku_xjgn5lw6.users.$username_1 dup key: { : "test@test.com" }, stack=MongoError: E11000 duplicate key error index: heroku_xjgn5lw6.users.$username_1 dup key: { : "test@test.com" }
2019-08-23T16:41:28.725611+00:00 app[web.1]:     at Function.create (/app/node_modules/mongodb-core/lib/error.js:43:12)
2019-08-23T16:41:28.725613+00:00 app[web.1]:     at toError (/app/node_modules/mongodb/lib/utils.js:149:22)
2019-08-23T16:41:28.725619+00:00 app[web.1]:     at coll.s.topology.insert (/app/node_modules/mongodb/lib/operations/collection_ops.js:859:39)
2019-08-23T16:41:28.725620+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:397:18
2019-08-23T16:41:28.725629+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:61:11), driver=true, name=MongoError, index=0, code=11000, errmsg=E11000 duplicate key error index: heroku_xjgn5lw6.users.$username_1 dup key: { : "test@test.com" }
```

**Comment by Sh1karno** [comment]
**RETEST:**
- [x] Imposible to register with existing data

**TEST RESULT:**
AR=ER bug can be closed
